const certificates = [
  {
    id: 1,
    image: "src/assets/Generative ai.jpg",
    company: "Datagami Technology Services",
    location: "Online",
    startDate: "Jan 2026",
    endDate: "Mar 2026",
    technologies: [
      "Generative AI",
      "Large Language Models (LLMs)",
      "Prompt Engineering",
      "Python",
    ],
    skills: [
      "Generative AI Fundamentals",
      "Prompt Engineering",
      "AI Model Development",
      "Authentication",
    ],
    certificateUrl: "src/assets/Generative ai.jpg",
  },
  {
    id: 2,
    image: "src/assets/Agentic AI.jpg",
    company: "Datagami",
    location: "Online",
    startDate: "Apr 2026",
    endDate: "May 2026",
    technologies: [
      "Agentic AI",
      "Large Language Models (LLMs)",
      "AI Agents",
      "Python",
    ],
    skills: [
      "AI Agent Development",
      "Autonomous Task Execution",
      "Prompt Engineering",
      "LLM Integration",
    ],
    certificateUrl: "src/assets/Agentic AI.jpg",
  },
  {
    id: 3,
    image: "src/assets/devops foundation.jpg",
    company: "Datagami",
    location: "Online",
    startDate: "Jun 2025",
    endDate: "Jul 2025",
    technologies: [
      "DevOps",
      "Git",
      "GitHub",
      "Docker",
      "Jenkins",
      "Kubernetes",
    ],
    skills: [
      "DevOps Fundamentals",
      "Continuous Integration & Continuous Deployment (CI/CD)",
      "Version Control with Git",
      "Team Collaboration",
    ],
    certificateUrl: "src/assets/devops foundation.jpg",
  },
  {
    id: 4,
    image: "src/assets/InternPe.jpeg",
    company: "InternPe",
    location: "Online",
    startDate: "Jul 2024",
    endDate: "Aug 2024",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Design",
      "Problem Solving",
      "Version Control",
      "Frontend Development",
      "Debugging",
    ],
    certificateUrl: "src/assets/InternPe.jpeg",
  },
  {
    id: 5,
    image: "src/assets/OASIS INFOBYTE.jpg",
    company: "OASIS INFOBYTE",
    location: "Online",
    startDate: "Jan 2025",
    endDate: "Feb 2025",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Web Design",
      "Frontend Development",
      "Problem Solving",
      "Team Collaboration",
      "Version Control",
    ],
    certificateUrl: "src/assets/OASIS INFOBYTE.jpg",
  },
  {
    id: 5,
    image: "src/assets/PRODIGY INFOTECH.jpg",
    company: "Prodigy InfoTech",
    location: "Online",
    startDate: "01 Sep 2024",
    endDate: "30 Sep 2024",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Web Design",
      "Frontend Development",
      "Problem Solving",
      "Team Collaboration",
      "Version Control",
    ],
    certificateUrl: "src/assets/PRODIGY INFOTECH.jpg",
  },
];

export default certificates;
