const certificates = [
  {
    id: 1,
    image: "/assets/generative-ai.jpg",
    company: "Datagami Technology Services",
    location: "Online",
    startDate: "January 2026",
    endDate: "February 2026",
    technologies: [
      "Generative AI",
      "Large Language Models (LLMs)",
      "Prompt Engineering",
      "Python",
    ],
    skills: [
      "Generative AI Fundamentals",
      "Prompt Engineering",
      "AI Model Development",
      "Authentication",
    ],
    certificateUrl: "/assets/generative-ai.jpg",
  },
  {
    id: 2,
    image: "/assets/agentic-ai.jpg",
    company: "Datagami",
    location: "Online",
    startDate: "February 2026",
    endDate: "March 2026",
    technologies: [
      "Agentic AI",
      "Large Language Models (LLMs)",
      "AI Agents",
      "Python",
    ],
    skills: [
      "AI Agent Development",
      "Autonomous Task Execution",
      "Prompt Engineering",
      "LLM Integration",
    ],
    certificateUrl: "/assets/agentic-ai.jpg",
  },
  {
    id: 3,
    image: "/assets/devops-foundation.jpg",
    company: "Datagami",
    location: "Online",
    startDate: "April 2025",
    endDate: "May 2025",
    technologies: [
      "DevOps",
      "Git",
      "GitHub",
      "Docker",
      "Jenkins",
      "Kubernetes",
    ],
    skills: [
      "DevOps Fundamentals",
      "Continuous Integration & Continuous Deployment (CI/CD)",
      "Version Control with Git",
      "Team Collaboration",
    ],
    certificateUrl: "/assets/devops-foundation.jpg",
  },

  {
    id: 4,
    image: "/assets/oasis-infobyte.jpg",
    company: "OASIS INFOBYTE",
    location: "Online",
    startDate: "January 2025",
    endDate: "February 2025",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Web Design",
      "Frontend Development",
      "Problem Solving",
      "Team Collaboration",
      "Version Control",
    ],
    certificateUrl: "/assets/oasis-infobyte.jpg",
  },
  {
    id: 5,
    image: "/assets/prodigy-infotech.jpg",
    company: "Prodigy InfoTech",
    location: "Online",
    startDate: "01 September 2024",
    endDate: "30 September 2024",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Web Design",
      "Frontend Development",
      "Problem Solving",
      "Team Collaboration",
      "Version Control",
    ],
    certificateUrl: "/assets/prodigy-infotech.jpg",
  },
    {
    id: 6,
    image: "/assets/internpe.jpeg",
    company: "InternPe",
    location: "Online",
    startDate: "July 2024",
    endDate: "August 2024",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Git", "GitHub"],
    skills: [
      "Web Development",
      "Responsive Design",
      "Problem Solving",
      "Version Control",
      "Frontend Development",
      "Debugging",
    ],
    certificateUrl: "/assets/internpe.jpeg",
  },
];

export default certificates;
